version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: prometheus-grafana-dashboard-app
    container_name: dashboard-app
    ports:
      - "8080:8080"
    networks:
      - monitoring-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring-net

networks:
  monitoring-net:
    driver: bridge

